### ISSUE TITLE
Adding new experiments on Arduino Interfacing using Python

### ISSUE THREAD

**Issue by deepampriyadarshi** [FOSSEE/FLOSS-Arduino-Book#1]
Current textbook has very limited number of experiments. So I want to update it by adding LCD interfacing and programming using pySerial library of python.

**Comment by SudhakarKuma** [comment]
Of course, you can add LCD experiments. I believe you will make use of existing [firmware](https://github.com/FOSSEE/FLOSS-Arduino-Book/tree/master/tools/floss-firmware) to build your experiments.

**Comment by deepampriyadarshi** [comment]
> Of course, you can add LCD experiments. I believe you will make use of existing [firmware](https://github.com/FOSSEE/FLOSS-Arduino-Book/tree/master/tools/floss-firmware) to build your experiments.

Sir, Am I allowed to modify that **firmware** also? Since the existing one doesn't include **LiquidCrystal** library and interfacing with manual digital pins will be a very cumbersome process.

**Comment by SudhakarKuma** [comment]
Yes, you can modify the firmware. However, it would be best if you modified it so that the existing experiments are not affected.

**Comment by deepampriyadarshi** [comment]
Actually @SudhakarKuma Sir I have certain issue. I am under **FOSSEE club of Vellore Institute of Technology, Chennai**. This club is directly **coordinated by IITB**. Every year (including this year also) **FOSSEE club of VIT, Chennai** run a sort of Internship Program where they select students to work on any FOSSEE project (Textbook Companion, Lab Migration, Circuit Simulation etc.) This year I got selected for FLOSS-Arduino
So I think it will be better submit my contributions through them.
